fix notice on __get error
Ocramius/ProxyManager pull request #357
Opened 2016-12-21 06:43 UTC by sakarikl

If backtrace does not have file or line data error string generating caused notice

2016-12-22 14:20 UTC, Ocramius requested changes

2016-12-22 14:20 UTC, Ocramius commented on src/ProxyManager/ProxyGenerator/Util/PublicScopeSimulator.php
> +            . '            $backtrace[0][\'file\'] ?? \'\',' . "\n"
In which scenarios would this be the case? Can you add a functional test (`.phpt`)?

2016-12-23 07:03 UTC, sakarikl commented on src/ProxyManager/ProxyGenerator/Util/PublicScopeSimulator.php
> +            . '            $backtrace[0][\'file\'] ?? \'\',' . "\n"
Code like this:

`
class Foo {
    private $value = 'Value';
}

class Bar  extends Foo{
}

$factory = new \ProxyManager\Factory\LazyLoadingValueHolderFactory();
$proxy = $factory->createProxy(
    \Bar::class,
    function (& $wrappedObject, $proxy, $method, $parameters, & $initializer) {
        $wrappedObject = new Bar(); // instantiation logic here
        $initializer   = null; // turning off further lazy initialization
    }
);

$r = new \ReflectionClass(\Foo::class);
$p = $r->getProperty('value');
$p->setAccessible(true);

$p->getValue($proxy);
`

causes output:

PHP Notice:  Undefined index: file in /vendor/ocramius/proxy-manager/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php(70) : eval()'d code on line 85

PHP Notice:  Undefined index: line in /vendor/ocramius/proxy-manager/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php(70) : eval()'d code on line 86

PHP Notice:  Undefined property: Bar::$value in  on line  in /vendor/ocramius/proxy-manager/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php(70) : eval()'d code on line 88

2016-12-23 12:10 UTC, Ocramius commented
Ah yes, internal reflection produces no file/line in a trace, good point!

On 23 Dec 2016 08:03, "sakarikl" <notifications@github.com> wrote:

> *@sakarikl* commented on this pull request.
> ------------------------------
>
> In src/ProxyManager/ProxyGenerator/Util/PublicScopeSimulator.php
> <https://github.com/Ocramius/ProxyManager/pull/357>:
>
> > @@ -108,8 +108,8 @@ private static function getUndefinedPropertyNotice(string $operationType, string
>              . '            \'Undefined property: %s::$%s in %s on line %s\',' . "\n"
>              . '            get_parent_class($this),' . "\n"
>              . '            $' . $nameParameter . ',' . "\n"
> -            . '            $backtrace[0][\'file\'],' . "\n"
> -            . '            $backtrace[0][\'line\']' . "\n"
> +            . '            $backtrace[0][\'file\'] ?? \'\',' . "\n"
>
> Code like this:
>
> `
> class Foo {
> private $value = 'Value';
> }
>
> class Bar extends Foo{
> }
>
> $factory = new \ProxyManager\Factory\LazyLoadingValueHolderFactory();
> $proxy = $factory->createProxy(
> \Bar::class,
> function (& $wrappedObject, $proxy, $method, $parameters, & $initializer) {
> $wrappedObject = new Bar(); // instantiation logic here
> $initializer = null; // turning off further lazy initialization
> }
> );
>
> $r = new \ReflectionClass(\Foo::class);
> $p = $r->getProperty('value');
> $p->setAccessible(true);
>
> $p->getValue($proxy);
> `
>
> causes output:
>
> PHP Notice: Undefined index: file in /vendor/ocramius/proxy-
> manager/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php(70)
> : eval()'d code on line 85
>
> PHP Notice: Undefined index: line in /vendor/ocramius/proxy-
> manager/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php(70)
> : eval()'d code on line 86
>
> PHP Notice: Undefined property: Bar::$value in on line in
> /vendor/ocramius/proxy-manager/src/ProxyManager/GeneratorStrategy/
> EvaluatingGeneratorStrategy.php(70) : eval()'d code on line 88
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Ocramius/ProxyManager/pull/357>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAJakKu_J4y9HXPNELNUQEwEcVsSiuWzks5rK3IpgaJpZM4LSoRe>
> .
>

2016-12-24 14:30 UTC, Ocramius commented
While trying to check for a suitable test case, I found that this actually hits a known edge case ( https://github.com/Ocramius/ProxyManager/pull/299 ). Currently unsure if fixable, since the code should work without failures in this scenario:

```php
class Foo {
    private $value = 'Value';
}

class Bar  extends Foo{
}

$factory = new \ProxyManager\Factory\LazyLoadingValueHolderFactory();
$proxy = $factory->createProxy(
    \Bar::class,
    function (& $wrappedObject, $proxy, $method, $parameters, & $initializer) {
        $wrappedObject = new Bar(); // instantiation logic here
        $initializer   = null; // turning off further lazy initialization
    }
);

$r = new \ReflectionClass(\Foo::class);
$p = $r->getProperty('value');
$p->setAccessible(true);

$p->getValue($proxy);
```

2016-12-24 14:53 UTC, Ocramius commented
Indeed, I cannot reproduce this outside of this scenario (which is already broken).

Tried various proxy types, but this one seems to be the only affected one...

2020-12-20 16:06 UTC, closed without merging