Upgrade to PHPUnit ^9.4
Ocramius/ProxyManager pull request #640
Opened 2020-12-18 07:07 UTC by martinssipenko

2020-12-20 17:47 UTC, Ocramius requested changes

2020-12-20 17:47 UTC, Ocramius commented on composer.lock
> +            "version": "3.18.2",
Please do a `git revert` on `composer.lock`, then try a `composer update phpunit/phpunit` to isolate out this `vimeo/psalm` upgrade.

`vimeo/psalm` is correct here (in the issues reported in this patch), but that's my problem to solve later :-)

2020-12-21 07:30 UTC, martinssipenko commented
Was not as easy as you described because of PHPUnit's and Psalms' common dependencies, but I think I managed to achieve to upgrade PHPUnit and only its dependencies that had to be upgraded.

2020-12-21 09:29 UTC, Ocramius approved these changes
LGTM, thanks @martinssipenko!

2020-12-21 09:29 UTC, merged