Bump vimeo/psalm from 4.4.1 to 4.6.3
Ocramius/ProxyManager pull request #675
Opened 2021-03-15 21:57 UTC by malukenho

Favor this PR over https://github.com/Ocramius/ProxyManager/pull/674

2021-03-16 09:21 UTC, Ocramius requested changes

2021-03-16 09:21 UTC, Ocramius commented on tests/ProxyManagerTest/Functional/AccessInterceptorScopeLocalizerFunctionalTest.php
> +        /** @psalm-var AccessInterceptorInterface<object>&ClassWithPublicProperties $proxy */
`<object>` should be `<ClassWithPublicProperties>`

2021-03-16 09:21 UTC, Ocramius commented on tests/ProxyManagerTest/Functional/AccessInterceptorScopeLocalizerFunctionalTest.php
> +        /** @psalm-var AccessInterceptorInterface<object>&ClassWithPublicProperties $proxy */
`<object>` should be `<ClassWithPublicProperties>`

2021-03-16 09:21 UTC, Ocramius commented on tests/ProxyManagerTest/Functional/AccessInterceptorScopeLocalizerFunctionalTest.php
> +        /** @psalm-var AccessInterceptorInterface<object>&ClassWithPublicArrayPropertyAccessibleViaMethod $proxy */
`<object>` should be `<ClassWithPublicArrayPropertyAccessibleViaMethod>`

2021-03-16 09:21 UTC, Ocramius commented on tests/ProxyManagerTest/Functional/AccessInterceptorScopeLocalizerFunctionalTest.php
>          assert($proxy instanceof AccessInterceptorInterface);
These assertions become redundant now, no?

2021-03-16 12:45 UTC, malukenho commented
I've tried your suggestions before — and tried it again right now. why not? — it didn't work 😬

2021-03-16 12:54 UTC, Ocramius commented
> it didn't work :grimacing: 

What didn't work?

2021-03-16 13:05 UTC, malukenho commented
All of your review comments.

2021-03-16 13:11 UTC, Ocramius commented
Yes, but what didn't work? :D

2021-03-22 21:47 UTC, malukenho commented
The changes on the psalm comments you suggested. It basically gave me the similar errors to the #674

2021-07-13 21:58 UTC, closed without merging